name: Publish

on:
  push:
    branches: 
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          
      - run: npm run test
        env:
          TEST_EXPECTED: "2022-01-01T13:00:00.000Z"

      - run: npm run deploy
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}